export const kycData = {
  cynopsis1: true,
  cynopsis2: false,
  cynopsis3: false,
  cynopsis4: true,
  cynopsis5: true,
  cynopsis6: false,
  cynopsis7: true,
  cynopsis8: true,
  cynopsis9: false,
  cynopsis10: true,
  corporateName: 'Lorem Ipsum',
  registrationNumber: '46549879',
  legalentityStatus: 'Lorem Ipsum',
  countryOfIncorporation: 'Algeria',
  others: 'Cras ultricies ligula sed magna dictum porta',
  sourceOfFounds: 'Cras ultricies',
  businessActivity: 'ligula',
  ownership: 'Cras',
  entityType: 'porta',
  fullName: 'Vestibulum',
  designation: 'Lorem Ipsum',
  email: 'ion.leahu@titanium-tech.net',
  phoneNumber: '+1 654 65 44 56',
  line1: 'Vestibulum',
  line2: 'Lorem Ipsum',
  city: 'Lorem Ipsum',
  state: 'Vestibulum',
  zip: '6812',
  country: 'Algeria',
  line1Residential: 'Vestibulum',
  line2Residential: 'Lorem Ipsum',
  cityResidential: 'Lorem Ipsum',
  stateResidential: 'Vestibulum',
  zipResidential: '6812',
  countryResidential: 'Algeria',
  sourceOfFunds1: true,
  sourceOfFunds2: false,
  sourceOfFunds3: false,
  sourceOfFunds4: true,
  sourceOfFunds5: true,
  sourceOfFunds6: false,
  sourceOfFunds7: true,
  sourceOfFunds8: true,
  sourceOfFunds9: false,
  sourceOfFunds10: true,
  investorStatusDeclaration1: true,
  investorStatusDeclaration2: false,
  investorStatusDeclaration3: false,
  investorStatusDeclaration4: false,
  investorStatusDeclaration5: false,
  investorStatusDeclaration6: false,
  fatca1: true,
  fatca2: true,
  optInRequirement1: true,
  optInRequirement2: true,
  optInRequirement3: true,
  countryOfTaxresidency: 'Vestibulum',
  taxIdentification: 'Vestibulum',
  beneficialFullName: 'Vestibulum',
  percentageShareholding: 'Lorem Ipsum',
} as Record<string, any>
