import React from 'react'
import { Typography, Grid, Link, Box } from '@material-ui/core'
import appStoreLogo from '../assets/appstore.png'
import googlePlayLogo from '../assets/googleplay.png'
import { StepWrapper } from 'app/pages/security/pages/setup2fa/components/StepWrapper'

export const Step1Download = () => (
  <StepWrapper title='Install Authenticator App in Your Smartphone Device'>
    <Grid container direction='column' spacing={3} alignItems='center'>
      <Grid item xs={12} md={8} lg={6}>
        <Typography align='center' variant='body1'>
          When you log in, you’ll need to enter a code generated by the Google
          Authenticator app or another authenitcator app
        </Typography>
      </Grid>
      <Grid item xs={12} md={8} lg={6}>
        <Typography align='center' variant='body1'>
          Download an authentication app to your smartphone from the App Store
          (for iPhone) or Google Play (for android smartphones)
        </Typography>
      </Grid>
      <Grid item>
        <Box paddingY={4}>
          <Grid container justifyContent='center' spacing={2}>
            <Grid item>
              <Link
                href='https://apps.apple.com/us/app/google-authenticator/id388497605'
                target='_blank'
              >
                <img height='40px' src={appStoreLogo} alt='App Store Logo' />
              </Link>
            </Grid>
            <Grid item>
              <Link
                href='https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en'
                target='_blank'
              >
                <img
                  height='40px'
                  src={googlePlayLogo}
                  alt='Google Play Logo'
                />
              </Link>
            </Grid>
          </Grid>
        </Box>
      </Grid>
      <Grid item xs={12} md={8} lg={6}>
        <Typography align='center' variant='body1'>
          Please click “NEXT” when you have finished the authenticator app
          installed in your smartphone
        </Typography>
      </Grid>
    </Grid>
  </StepWrapper>
)
