export const devCreds = {
  HOST: `api.dev.mozork.com`,
  BASE_API: `https://api.dev.mozork.com/`,
  URL: 'https://dev.mozork.com/',
  EMAIL: 'xosugysu@mailinator.com',
  EMAIL_APPROVED: 'email_issuer_corporate@mailinator.com',
  // BANK_ACCOUNT: 'bank_account_test@mailinator.com',
  EMAIL_FOR_RESET: 'luch41635754715203@wwjmp.com',
  CREATE_DSO_MORE_OPTIONS: 'individual@mailinator.com',
  VIEW_DSO_MORE_OPTIONS: 'email_issuer_corporate@mailinator.com',
  ADMIN: 'oleksiy@investax.io',
  PASSWORD: 'Pa$$w0rd!qwe',
  DSO_EDIT: 'email_issuer_corporate@mailinator.com', // bug
  INVESTOR: 'luch41648638381405@wwjmp.com',
  AUTHORIZER_USER: 'authorizerTestsDEV@esiix.com', //'authorizerTestsDEV@esiix.com',
  ADMIN_SECTION: 'adminsectiontestsdev@esiix.com',
  RIGHTS: 'test_dev_exchange_2_user@esiix.com',
  USER_DISABLE_ENABLE: 'test_dev_exchange_3_user@esiix.com',
  VIRTUAL_ACCOUNT: 'test_dev_exchange_2_user@esiix.com',
  firstExchange: 'test_dev_exchange_1_user@esiix.com',
  firstUserId: '61e1640547ade252462cec89',
  secondExchange: 'test_dev_exchange_2_user@esiix.com',
  secondUserId: '61e167f447ade252462cf19e',
  thirdExchange: 'test_dev_exchange_3_user@esiix.com',
  thirdUserId: '61e1696047ade252462cf361'
}
