export const devCreds = {
  HOST: `api.dev.mozork.com`,
  BASE_API: `https://api.dev.mozork.com/`,
  URL: 'https://dev.mozork.com/',
  EMAIL: '',
  EMAIL_APPROVED: '',
  VIEW_PROFILE_EMAIL: '',
  BANK_ACCOUNT: '',
  EMAIL_FOR_RESET: '',
  CREATE_DSO_MORE_OPTIONS: '',
  VIEW_DSO_MORE_OPTIONS: '',
  PASSWORD: 'Pa$$w0rd!qwe',
  PASSWORD_RESET: 'Pa$$w0rd!qwe1A',
  EDIT_CORPORATE: '',
  EDIT_INDIVIDUAL: '',
  EDIT_ISSUER: '',
  DSO_EDIT: '',
  MAIL_FOR_CAPITAL_CALL: '',
  AUTHORIZER_USER: '',
  ADMIN_SECTION: '',
  RIGHTS: '',
  USER_DISABLE_ENABLE: '',
  VIRTUAL_ACCOUNT: '',
  INVESTOR_HEX: '',

  firstExchange: 'test_dev_exchange_1_user@esiix.com',
  firstUserId: '61e1640547ade252462cec89',
  secondExchange: 'test_dev_exchange_2_user@esiix.com',
  secondUserId: '61e167f447ade252462cf19e',
  thirdExchange: 'test_dev_exchange_3_user@esiix.com',
  thirdUserId: '61e1696047ade252462cf361'
}
