export const stagingCreds = {
  HOST: `api.staging.mozork.com`,
  BASE_API: `https://api.staging.mozork.com/`,
  URL: 'https://staging.mozork.com/',
  EMAIL: 'xe2v112a@mailinator.com',
  EMAIL_APPROVED: 'lopezmichaela1b031@gmail.com',
  // BANK_ACCOUNT: 'byjywarago@mailinator.com',
  EMAIL_FOR_RESET: 'luch41635754715203@wwjmp.com',
  CREATE_DSO_MORE_OPTIONS: 'lorepag@mailinator.com',
  VIEW_DSO_MORE_OPTIONS: 'qyle@mailinator.com',
  ADMIN: 'oleksiyk@titanium-tech.net',
  PASSWORD: 'Pa$$w0rd!qwe',
  INVESTOR: 'luch41638787427054@wwjmp.com',
  DSO_EDIT: 'dsoCorporateUser@mailinator.com',
  AUTHORIZER_USER: 'authorizerTests@esiix.com',
  ADMIN_SECTION: 'adminsectiontests@esiix.com',
  RIGHTS: 'pochtamoyapochta123+secondechange@gmail.com',
  USER_DISABLE_ENABLE: 'pochtamoyapochta123+firstexchange@gmail.com', //61dbf9f4c9056c0daf9c92ea
  VIRTUAL_ACCOUNT: 'pochtamoyapochta123+secondEchange@gmail.com',
  firstExchange: 'pochtamoyapochta123+firstexchange@gmail.com',
  firstUserId: '61dbf9f4c9056c0daf9c92ea',
  secondExchange: 'pochtamoyapochta123+secondEchange@gmail.com',
  secondUserId: '',
  thirdExchange: 'pochtamoyapochta123+thirdExchange@gmail.com',
  thirdUserId: ''
}
