import makeStyles from '@mui/styles/makeStyles'

export const useStyles = makeStyles(theme => ({
  basicStyle: {
    fontFamily: 'Inter',
    opacity: 0.5,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px 16px',
    width: '101px',
    height: '36px',
    background: '#F7F9FA',
    borderRadius: '56px'
  },
  basicDarkStyle: {
    fontFamily: 'Inter',
    opacity: 0.5,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px 16px',
    width: '101px',
    height: '36px',
    background: '#1D3667',
    borderRadius: '56px',
    color: '#89A1CE'
  },
  specialStyle: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px 16px',
    width: '49px',
    height: '36px',
    background: '#FFFFFF',
    border: '1px solid rgba(76, 136, 255, 0.2)',
    boxSizing: 'border-box',
    boxShadow: '0px 4px 4px rgba(162, 172, 191, 0.08)',
    borderRadius: '56px',
    color: '#4C88FF',
    fontFamily: 'Inter'
  },
  specialDarkStyle: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px 16px',
    width: '49px',
    height: '36px',
    background: '#152D5F',
    border: '1px solid rgba(76, 136, 255, 0.2)',
    boxSizing: 'border-box',
    boxShadow: '0px 4px 4px rgba(162, 172, 191, 0.08)',
    borderRadius: '56px',
    color: '#4C88FF',
    fontFamily: 'Inter'
  },
  successStyle: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px 24px',
    width: '160px',
    height: '37px',
    background: 'rgba(125, 211, 32, 0.15)',
    borderRadius: '8px',
    color: '#7DD320',
    fontFamily: 'Inter'
  },
  warningStyle: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px 24px',
    width: '160px',
    height: '37px',
    background: 'rgba(255, 201, 0, 0.1)',
    borderRadius: '8px',
    color: '#FFC900',
    fontFamily: 'Inter'
  },
  errorStyle: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px 24px',
    width: '160px',
    height: '37px',
    background: 'rgba(255, 128, 128, 0.1)',
    borderRadius: '8px',
    color: '#FF8080',
    fontFamily: 'Inter'
  },
  unknownStyle: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '10px 24px',
    width: '160px',
    height: '37px',
    background: 'rgba(190, 196, 207, 0.15)',
    borderRadius: '8px',
    color: '#778194',
    fontFamily: 'Inter'
  }
}))
