/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides
} from 'ethers'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import type { TypedEventFilter, TypedEvent, TypedListener } from './common'

interface IxsFaucetAbiInterface extends ethers.utils.Interface {
  functions: {
    'deleteAddrFromWhitelist(address)': FunctionFragment
    'faucet()': FunctionFragment
    'renounceOwnership()': FunctionFragment
    'setAddrToWhitelist(address)': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'erc20Address()': FunctionFragment
    'getStatusAddrFromWhitelist(address)': FunctionFragment
    'getTimeToFaucet()': FunctionFragment
    'owner()': FunctionFragment
  }

  encodeFunctionData(
    functionFragment: 'deleteAddrFromWhitelist',
    values: [string]
  ): string
  encodeFunctionData(functionFragment: 'faucet', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'setAddrToWhitelist',
    values: [string]
  ): string
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [string]
  ): string
  encodeFunctionData(
    functionFragment: 'erc20Address',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'getStatusAddrFromWhitelist',
    values: [string]
  ): string
  encodeFunctionData(
    functionFragment: 'getTimeToFaucet',
    values?: undefined
  ): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string

  decodeFunctionResult(
    functionFragment: 'deleteAddrFromWhitelist',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'faucet', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setAddrToWhitelist',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'erc20Address',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getStatusAddrFromWhitelist',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getTimeToFaucet',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result

  events: {
    'Faucet(address,uint256)': EventFragment
    'OwnershipTransferred(address,address)': EventFragment
    'Whitelist(address)': EventFragment
    'WhitelistRemovedAddress(address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'Faucet'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Whitelist'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'WhitelistRemovedAddress'): EventFragment
}

export type FaucetEvent = TypedEvent<
  [string, BigNumber] & { to: string; amount: BigNumber }
>

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>

export type WhitelistEvent = TypedEvent<[string] & { whitelistAddress: string }>

export type WhitelistRemovedAddressEvent = TypedEvent<
  [string] & { whitelistAddress: string }
>

export class IxsFaucetAbi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this

  listeners(eventName?: string): Array<Listener>
  off(eventName: string, listener: Listener): this
  on(eventName: string, listener: Listener): this
  once(eventName: string, listener: Listener): this
  removeListener(eventName: string, listener: Listener): this
  removeAllListeners(eventName?: string): this

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

  interface: IxsFaucetAbiInterface

  functions: {
    deleteAddrFromWhitelist(
      _whitelistAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    faucet(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    setAddrToWhitelist(
      _whitelistAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    erc20Address(overrides?: CallOverrides): Promise<[string]>

    getStatusAddrFromWhitelist(
      _whitelistAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    getTimeToFaucet(overrides?: CallOverrides): Promise<[BigNumber]>

    owner(overrides?: CallOverrides): Promise<[string]>
  }

  deleteAddrFromWhitelist(
    _whitelistAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  faucet(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  setAddrToWhitelist(
    _whitelistAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  erc20Address(overrides?: CallOverrides): Promise<string>

  getStatusAddrFromWhitelist(
    _whitelistAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>

  getTimeToFaucet(overrides?: CallOverrides): Promise<BigNumber>

  owner(overrides?: CallOverrides): Promise<string>

  callStatic: {
    deleteAddrFromWhitelist(
      _whitelistAddress: string,
      overrides?: CallOverrides
    ): Promise<void>

    faucet(overrides?: CallOverrides): Promise<void>

    renounceOwnership(overrides?: CallOverrides): Promise<void>

    setAddrToWhitelist(
      _whitelistAddress: string,
      overrides?: CallOverrides
    ): Promise<void>

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>

    erc20Address(overrides?: CallOverrides): Promise<string>

    getStatusAddrFromWhitelist(
      _whitelistAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>

    getTimeToFaucet(overrides?: CallOverrides): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<string>
  }

  filters: {
    'Faucet(address,uint256)'(
      to?: null,
      amount?: null
    ): TypedEventFilter<[string, BigNumber], { to: string; amount: BigNumber }>

    Faucet(
      to?: null,
      amount?: null
    ): TypedEventFilter<[string, BigNumber], { to: string; amount: BigNumber }>

    'OwnershipTransferred(address,address)'(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >

    'Whitelist(address)'(
      whitelistAddress?: null
    ): TypedEventFilter<[string], { whitelistAddress: string }>

    Whitelist(
      whitelistAddress?: null
    ): TypedEventFilter<[string], { whitelistAddress: string }>

    'WhitelistRemovedAddress(address)'(
      whitelistAddress?: null
    ): TypedEventFilter<[string], { whitelistAddress: string }>

    WhitelistRemovedAddress(
      whitelistAddress?: null
    ): TypedEventFilter<[string], { whitelistAddress: string }>
  }

  estimateGas: {
    deleteAddrFromWhitelist(
      _whitelistAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    faucet(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    setAddrToWhitelist(
      _whitelistAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    erc20Address(overrides?: CallOverrides): Promise<BigNumber>

    getStatusAddrFromWhitelist(
      _whitelistAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getTimeToFaucet(overrides?: CallOverrides): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    deleteAddrFromWhitelist(
      _whitelistAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    faucet(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    setAddrToWhitelist(
      _whitelistAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    erc20Address(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getStatusAddrFromWhitelist(
      _whitelistAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getTimeToFaucet(overrides?: CallOverrides): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
