name: Build & Deploy Develop
on:
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Build and Optimize for Production
        env:
          REACT_APP_API_URL: https://devapi.mozork.com
        run: npm install && npm run build
      - name: Deploy Build to S3 bucket
        run: npm run deploy
        env:
          AWS_BUCKET: app.mozork.com
          AWS_REGION: ap-southeast-1
          AWS_DISTRO_ID: E1GXVB58NJXJTB

